### ISSUE TITLE
ImportError

### ISSUE THREAD

**Issue by kuang777** [man-group/dtale#656]
cannot import name '_centered' from 'scipy.signal.signaltools'

**Comment by seankmartin** [comment]
I had the same issue arising from an issue with the statsmodels and scipy packages.

Specifically, I had statsmodels version 0.13.0 and scipy 1.8.0 which caused this.

I fixed it by `pip install --upgrade statsmodels` to upgrade to version 0.13.2

**Comment by aschonfeld** [comment]
@seankmartin which version of python were you working with?  These are the current dependency settings for `scipy` & `statsmodels`:
```
scipy==1.2.3; python_version == '2.7'
scipy<=1.5.4; python_version == '3.0'
scipy<=1.5.4; python_version == '3.1'
scipy<=1.5.4; python_version == '3.2'
scipy<=1.5.4; python_version == '3.3'
scipy<=1.5.4; python_version == '3.4'
scipy<=1.5.4; python_version == '3.5'
scipy<=1.5.4; python_version == '3.6'
scipy==1.7.3; python_version == '3.7'
scipy; python_version >= '3.8'
statsmodels==0.10.2; python_version == '2.7'
statsmodels==0.12.2; python_version == '3.0'
statsmodels==0.12.2; python_version == '3.1'
statsmodels==0.12.2; python_version == '3.2'
statsmodels==0.12.2; python_version == '3.3'
statsmodels==0.12.2; python_version == '3.4'
statsmodels==0.12.2; python_version == '3.5'
statsmodels==0.12.2; python_version == '3.6'
statsmodels==0.12.2; python_version == '3.7'
statsmodels; python_version >= '3.8'
```

So if you're working with python 3.8 or higher both should be unpinned

**Comment by seankmartin** [comment]
@aschonfeld Thanks for the reply, I'm on Python 3.8.
I figured this issue was probably from my environment setup, was just posting my fix in case it helped @kuang777

**Comment by kuang777** [comment]
Thanks
